apiVersion: v1
kind: Secret
metadata:
  name: mvp-springboot-jdk17
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data: 
  password: github_pat_token
  username: github_user
stringData:
  name: mvp-springboot-jdk17
  url: https://github.com/axccoe/mvp-springboot-jdk17
  insecure: "true"
  project: default
  type: git
type: Opaque
