apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mvp-springboot-jdk17
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: mvp-springboot-dev
    server: ''
  source:
    path: manifests/overlays/dev
    repoURL: https://github.com/axccoe/mvp-springboot-jdk17.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
